// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Position struct {
	ID      int64
	TrackID int64
	T       int64
	Lon     float64
	Lat     float64
	SogMs   sql.NullFloat64
	CogRad  sql.NullFloat64
	Src     sql.NullString
	Qual    sql.NullInt64
}

type PositionsRtree struct {
	ID   int64
	Minx float64
	Maxx float64
	Miny float64
	Maxy float64
}

type Track struct {
	ID        int64
	Name      string
	StartedAt int64
	EndedAt   sql.NullInt64
	DistanceM sql.NullFloat64
	Notes     sql.NullString
}
