// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Position struct {
	ID      int64           `json:"id"`
	TrackID int64           `json:"track_id"`
	T       int64           `json:"t"`
	Lon     float64         `json:"lon"`
	Lat     float64         `json:"lat"`
	SogMs   sql.NullFloat64 `json:"sog_ms"`
	CogRad  sql.NullFloat64 `json:"cog_rad"`
	Src     sql.NullString  `json:"src"`
	Qual    sql.NullInt64   `json:"qual"`
}

type Track struct {
	ID        int64           `json:"id"`
	Name      string          `json:"name"`
	StartedAt int64           `json:"started_at"`
	EndedAt   sql.NullInt64   `json:"ended_at"`
	DistanceM sql.NullFloat64 `json:"distance_m"`
	Notes     sql.NullString  `json:"notes"`
}
